import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Reference Documentation',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'doc',
      id: 'CHANGELOG',
      label: 'Changelog',
    },
  ],
};

export default sidebars;
